//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentsAccount
    {
        public long ID { get; set; }
        public string Identification { get; set; }
        public long Balance { get; set; }
        public string StateAccounts { get; set; }
        public string numberAccounts { get; set; }
    
        public virtual User User { get; set; }
    }
}
